### ISSUE TITLE
StandardRecord's FwdDeclare.h isn't part of the sbnana product

### ISSUE THREAD

**Issue by cjbackhouse** [SBNSoftware/sbnana#12]
With a local checkout, this file (and `SRProxy.h`) are generated as part of the build, and I have them at
`localProducts*/sbnana/v09_19_00/include/sbnana/CAFAna/StandardRecord/Proxy/`

Whereas `setup sbnana v09_19_00 -qe19:prof; ls $SBNANA_INC/sbnana/CAFAna/StandardRecord/` only shows `SREnums.h`, and no sign of the `Proxy/` subdirectory at all.

I assumed the ups products were essentially made from the appropriate localProducts directory. Is it more complicated than that? Why are these files missed?

Ed correctly points out that we will want this to be working in time for the next workshop (ie in the upcoming release) so users don't have to check out and build the whole package. I am blaming this on something in the packaging step, so assigning Wes, though it's certainly possible that conditions during that build confuse my makefile.

**Comment by wesketchum** [comment]
Testing now ... sorry for the delay.
