### ISSUE TITLE
Support flatcafs in concat_cafs

### ISSUE THREAD

**Issue by cjbackhouse** [SBNSoftware/sbnana#73]
Currently the only way to get a concatted flatcaf is to concat first, and then flatten. It would definitely be convenient to go the other order too.

The code would be somewhat different to what exists for non-flat CAFs, but, at least for straight concatting with no other modifications, it should be very simple. You literally concatenate the TTrees, which there is presumably a ROOT function for.

**Comment by wesketchum** [comment]
@cjbackhouse Can you comment on the status of this/thinking on this now? Still needed?

**Comment by cjbackhouse** [comment]
Recently implemented :)
